export const politicsArticles = {


    article1: {
        text1: "Washington (CNN)Senate Republicans on Monday formally unveiled their roughly $1 trillion stimulus proposal, which includes a $400 cut in enhanced unemployment benefits, and will serve as an opening bid for bipartisan negotiations with Democrats while Congress scrambles to respond to the economic and public health crisis sparked by the coronavirus pandemic.",
        text2: "Senate Majority Leader Mitch McConnell said In comments on the Senate floor, \"The American people need more help,\" and that the GOP proposal will be called the HEALS Act, an acronym for Health, Economic Assistance, Liability Protection and Schools.",
        text3: "The bill will include a variety of component parts, which GOP senators and committee chairman rolled out in a series of floor speeches Monday evening, including liability protections, a second round of direct payments to Americans and a second round of Paycheck Protection Program loans intended to help keep the hardest-hit small businesses afloat. Perhaps the most immediately controversial aspect of the Senate Republican plan is that it includes a cut of $400 to the enhanced unemployment benefit for out of work Americans, a provision that generated swift backlash from Democrats.",
        id: 11
    },

    article2: {
        text1: "\"President Reagan was a proud Republican and supporter of a party that has carried on his fight for conservative principles of economic opportunity and limited government,\" RNC communications director Michael Ahrens told CNN in a statement. \"His likeness is used by thousands of Republicans each year who gather around the country for 'Reagan Dinners,' and his library regularly hosts debates for our presidential candidates.",
        text2: "Given that the Reagan Foundation just recently hosted the Trump family to raise money for its organization and has not objected to us using President Reagan's likeness before, their objection came as a surprise.\" RNC Chair Ronna McDaniel wrote in a tweet, \"The Republican Party has used President Reagan's image for decades. But since the Reagan Foundation is suddenly opposed to it, are they going to return the money @DonaldJTrumpJr and @kimguilfoyle raised for them just 8 months ago?\" before sharing a link to an event hosted by the foundation, featuring Donald Trump Jr., with proceeds benefiting the Reagan Foundation.",
        text3: "Ahrens also pointed to a number of events featuring members of the Trump family and administration benefiting the Reagan Foundation, telling CNN even though the RNC maintains their use of Reagan's likeness was \"appropriate,\" they'd pull the email pitch \"as a courtesy.\" Trump, and his campaign, directed ire at Fred Ryan, who works as the Washington Post's publisher and serves as chairman of the board of trustees for the California-based Reagan Foundation. \"So the Washington Post is running the Reagan Foundation,\" Trump tweeted Sunday, promising supporters, \"We will win anyway\" despite \"phony\" polls. \"It should be no surprise that the publisher and CEO of the Washington Post wants to interfere with President Trump's reelection campaign,\" Trump campaign communications director Tim Murtaugh told CNN. \"As Republicans, we all honor Ronald Reagan's contribution to this country and our party.\" The Reagan Foundation did not respond to a request for comment.",
         id: 12
    },

    article3: {
        text1: "Wrote House editor David Wasserman of Republicans: \"Now they're just trying to avoid a repeat of 2008, when they not only lost the presidency but got swamped by Democrats' money and lost even more House seats after losing 30 seats and control two years earlier. For the first time this cycle, Democrats have at least as good a chance at gaining House seats as Republicans on a net basis.\" The problems for Republicans are compounded by the massive fundraising disparity they face. \n    According to the Center for Responsive Politics, Democratic House candidates have raised $457 million so far in this election to $365 million for their GOP counterparts as of July 1. And the gap is even wider in the most competitive races; in a baker's dozen of most competitive races with primaries in June and July, Democratic incumbents have nearly nine(!) times more on hand -- $40 million to $4.5 million -- than the best-funded GOP challengers. Combine a declining national environment with that sort of fundraising problem and you have a recipe for House disaster for Republicans. *The Senate: At the start of the 2020 election, you'd have been hard-pressed to find a single national political handicapper willing to predict that Democrats would retake the chamber on November 3.",
        text2: "While the raw numbers looked good -- 23 Republican seats up as compared to 12 for Democrats -- the landscape was less favorable for the minority party. Just two Republican incumbents -- Sens. Cory Gardner in Colorado and Susan Collins in Maine -- are running in states Hillary Clinton won in 2016. Which means 21 of the 23 GOP seats are in places Trump won four years ago. And yet, as the election has worn on, the outlook has shifted considerably -- thanks, in large part, to Trump's rapidly declining fortunes and struggles by GOP incumbents to distance themselves from him. In Arizona, Sen. Martha McSally (R) looks dead in the water in her race against former astronaut Mark Kelly (D). Gardner is in deep trouble against former Gov. John Hickenlooper (D). And Collins is facing by far the biggest challenge of her political career in the form of state House Speaker Sara Gideon (D).",
        text3: "And those three seats are just the start of Senate Republicans' problems. Both seats in Georgia are in peril, as are North Carolina Sen. Thom Tillis, Iowa Sen. Joni Ernst, Montana Sen. Steve Daines and the open seat in Kansas. (Yes, Kansas!) By contrast, Democrats have only one real issue: Alabama Sen. Doug Jones (D), who will face off against former Auburn coach Tommy Tuberville in the fall. Jones, because of the state's strong Republican lean, could well do everything perfectly and still lose. (While Republicans talk about the vulnerability of Sen. Gary Peters in Michigan, there's not much evidence that race is going to be all that close.) What it all means is this: Democrats have a WIDE playing field on which to attempt to win the three seats they need if Biden wins the White House and four if Trump gets reelected. And at this point, they have to be considered favorites to do so, which is remarkable given where this two-year cycle started.",
        id: 13
    },

    article4: {
        text1: "(CNN)President Donald Trump's top aides are stepping up blame-game tactics against the states, saying coronavirus testing problems and rising cases are not his fault as they try to counter new polls suggesting that his leadership failings could cost him reelection. The move comes as Republicans on Capitol Hill haggle over a measure that would replace, with smaller benefits, $600 a week in federal aid to millions of workers that has already paid out for the last time, even as out-of-control virus spikes cause some states to slow or reverse opening plans.",
        text2: "The new administration drive to absolve Trump of responsibility and to speed up economic activity by encouraging people to go back to work follow the President's previously misjudged gamble to goad states that are now suffering terribly from the pandemic to open before they had properly suppressed the virus. It also coincides with his demands that all schools open while ignoring concerns of parents and teachers. With many states complaining that delays in processing coronavirus tests are making it impossible to check the spread of the disease, the administration claimed again on Sunday that its \"Manhattan Project\" on testing is sufficient.",
        text3: "We have enough tests right now, if we use them in the right way, to achieve the goals that we need to achieve,\" Adm. Brett Giroir, the administration's testing czar said on CNN's \"State of the Union.\" Giroir, who did allow that turnaround times for tests needed to improve, said states had not claimed all of the money allocated to build up test and tracing networks seen as critical to quelling the pandemic.",
        id: 14
    },

    article5: {
        text1: "(CNN)Melania Trump announced Monday she will oversee a renovation of the White House Rose Garden, overhauling the iconic greenspace adjacent to the Oval Office and West Wing. Trump intends to restore the space to more resemble the original design and formation of the Rose Garden, established by President John F. Kennedy, and implemented in 1962 by horticulturist and philanthropist Rachel \"Bunny\" Mellon. The renovation, which will include excavation, could take several weeks, according to a source familiar with the timeline, and the Rose Garden will, during that time, be out of commission for use. \"The very act of planting a garden involves hard work and hope in the possibility of a bright future,\" the first lady said in a statement. \"Preserving the history and beauty of the White House and its grounds is a testament to our nation's commitment to the care of this landscape and our dedication to American ideals, safeguarding them for our children and their children for generations to come.\" President Donald Trump has used the Rose Garden more frequently in recent weeks as a space to hold news conferences. In the era of Covid-19, the outdoor venue provides more safety from potential spread of the virus for journalists and guests, as medical experts maintain being outside is more optimal than gathering indoors.",
        text2: "The decision to revamp the Rose Garden was made several months ago, according to the source familiar with the first lady's plan. Renovations and large upkeep projects at the White House are oftentimes made during the month of August, when the first family is commonly away from Washington on summer vacation. In August 2017 and 2018, when the Trumps were in Bedminster, New Jersey, projects meant to repair and spruce up the White House took place. The Rose Garden is the latest White House renovation project for Trump, who already has revamped several spaces, including the White House bowling alley, the wall coverings in the Red Room, the furnishings in the Blue Room, the draperies in the Green Room and the rug in the Diplomatic Reception Room, to which she had added a border of the flowers representing each of the 50 states. Renovations of the White House's public rooms (the latter four) are funded by private donations to the White House Historical Association, a nonprofit institution that serves to oversee the conservation and upkeep of the People's House. The cost of the renovation of the bowling alley was covered by the Bowling Proprietors' Association of America, according to the White House.",
        text3: "The Rose Garden renovation will be financed with private donations, according to two sources familiar with the project. The White House did not comment. In March, as the coronavirus began to take hold in the United States, Trump was criticized for providing an update on another renovation she is spearheading: the White House Tennis Pavilion, a privately funded project on the South Lawn for use only by the first family and their guests. Trump first announced the pavilion renovation last October in a tweet featuring a picture of herself with a ceremonial shovel and a statement that said in part, \"It is my hope that this private space will function as a place to gather and spend leisure time for First Families.\" Trump's March post -- expressing her excitement and featuring photographs of the first lady wearing a hard hat and looking over apparent architectural plans -- met a plethora of negative reaction that seized on the first lady's post about a luxurious recreational venue despite a lack of public sentiments about the ongoing global pandemic and rising number of American deaths. The backlash prompted Trump to make a rare statement in her defense. \"I encourage everyone who chooses to be negative (and) question my work at the ‪@WhiteHouse to take time and contribute something good (and) productive in their own communities,\" she tweeted."
        , id: 15
    }
}